[env]
# Permits SQLX - cli to find the database
# https://github.com/launchbadge/sqlx/blob/main/sqlx-cli/README.md
DATABASE_URL = "sqlite://sqlite/primary.sqlite3"

#Permits usage of nightly-only, in-rfc UUID types, UUID7 is used most in Ceres
#https://github.com/uuid-rs/uuid/issues/523
#(This isnt true for current versions of uuid, but is for 1.3 which the cargo.toml pegs it at)
[target.'cfg(all())']
rustflags = ["--cfg", "uuid_unstable"]
